#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local url_chamber_Darwin="https://github.com/segmentio/chamber/releases/download/v${CHAMBER_VERSION}/chamber-v${CHAMBER_VERSION}-darwin-amd64"
  local url_chamber_Linux="https://github.com/segmentio/chamber/releases/download/v${CHAMBER_VERSION}/chamber-v${CHAMBER_VERSION}-linux-amd64"

  local url_chamber="url_chamber_$(uname -s)"
  local fnm_chamber="$(basename "${!url_chamber}")"
  cache curl "$fnm_chamber" "${!url_chamber}"

  mkdir -p "$shome/bin"
  pushd "$shome/bin"
  cp "${DATA}/cache/curl/$fnm_chamber" "$shome/bin/chamber"
  chmod 755 "$shome/bin/chamber"
  echo "${CHAMBER_VERSION}" > "$shome/.chamber-version"
  popd
}

main "$@"
