#!/usr/bin/env bash

function old_main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local url_chamber_Darwin="https://github.com/segmentio/chamber/releases/download/v${CHAMBER_VERSION}/chamber-v${CHAMBER_VERSION}-darwin-amd64"
  local url_chamber_Linux="https://github.com/segmentio/chamber/releases/download/v${CHAMBER_VERSION}/chamber-v${CHAMBER_VERSION}-linux-amd64"

  local url_chamber="url_chamber_$(uname -s)"
  local fnm_chamber="$(basename "${!url_chamber}")"
  cache curl "$fnm_chamber" "${!url_chamber}"

  mkdir -p "$shome/bin"
  pushd "$shome/bin"
  cp "${DATA}/cache/curl/$fnm_chamber" "$shome/bin/chamber"
  chmod 755 "$shome/bin/chamber"
  echo "${CHAMBER_VERSION}" > "$shome/.chamber-version"
  popd
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

	cd "$shome"
  export GOPATH="$shome"
	mkdir -p src/github.com/segmentio
	rm -rf src/github.com/segmentio/chamber
	git clone git@github.com:defn/chamber src/github.com/segmentio/chamber
  go get github.com/segmentio/chamber
}


main "$@"
