#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_chamber="0.0.1"
  jq -n --arg chamber "$ver_chamber" '{chamber: $chamber}'
}

version "$@"
